### PR TITLE
Making the Hifz Evalutator

### PR DESCRIPTION
**Pull request by bahaa96**
https://youtu.be/xC3g-CQXTAw

### CODE REVIEW

**Comment by abidlabs** [comment]
Looks really good Bahaa. Just some stylistic suggestions:
- It would be good to have a description of what we want the person to do. For example, we can say "After listening to the recording, please tell us did the user recite the correct verse?"
- Instead of the toggle buttons, which I think are maybe not so intuitive, what do you think about having a thumbs  up / thumbs down?
- What do you think about actually just presenting one verse at a time and one recording at a time? We could use a similar approach to this website: https://voice.mozilla.org/en/listen

**Comment by piraka9011** [comment]
Looks good, currently Evaluation get request returns a random ayah FYI. No button doesn't transition to next ayah.

**Comment by bahaa96** [comment]
@abidlabs Try it now.

**Comment by abidlabs** [comment]
Beautiful! The evaluation process looks amazing from an aesthetic point of view. I have a few suggestions:

* The font of the Arabic text is not the nice font that we use for the recitation page  (see screenshot). Can we use the same font, I think it should be just a font import.

image

* After I evaluated my first set of ayat, I got a popup message (which I love!) saying that I only evaluated 0 ayaat. Then after my next 5, I got a message saying that I evaluated 3 verses (see screenshot). I think the problem is that it loads the evaluation count _before_ the person does any evaluation counts. There should probably be a GET request when the person finishes their recitations to get an updated count.

image

* Some nits: we should move the CSS and JS that is currently in the evaluator.html page to separate CSS and JS files.

Otherwise, this looks so nice! And I think there is a clear need for evaluation... many recordings are empty.

**Comment by abidlabs** [comment]
Looks great to me!

**Pull request merged**
