### PR TITLE
Add Utnmanic font, render ayah as text

### PR DESCRIPTION
**Pull request by mohamedgomran**
@abidlabs I found the ayah is already a part of response of "get_ayah/" endpoint, I only rendered the text with the Uthmanic font.

For me_quran font, there is an issue with maad, the maad isn't rendered perfectly.

### CODE REVIEW

**Comment by abidlabs** [comment]
Can you show a screenshot of how the madd is rendered for you, @mohamedgomran?

**Comment by mohamedgomran** [comment]
@abidlabs 
Check this, on "meem".
image

**Comment by abidlabs** [comment]
Thanks for catching this @mohamedgomran. Before we push these changes, we should solve this issue, because it will certainly impact users' ability to read the text. One option is to do a bit of preprocessing of the loaded text: for example, it seems like we're having a problem with the "dagger alifs" being superimposed onto the "fatha", so if we see both the "dagger alif" and a "fatha", we should just discard the "fatha".

**Comment by mohamedgomran** [comment]
@abidlabs I checked the server response and I found that the returned text doesn't have the dagger alif with fatha.
And I think you have noticed, me_quran isn't smooth like KFGQPC Uthmanic Script HAFS (I used this one).

You can check a live example of all available fonts http://tanzil.net/#1:2, Tanzil uses the KFGQPC Uthman Taha Naskh which has some issues too because the live version has a modified text, it's not the same as the text they are providing for download.
The only font that is issues free is KFGQPC Uthmanic Script HAFS and it's very comfortable.
I suggest to keep using KFGQPC Uthmanic Script HAFS.
image

**Comment by tifa2UP** [comment]
@bahaa96 can we use this font for the mobile app as well?

**Pull request merged**
