### PR TITLE
Auth and serializer

### PR DESCRIPTION
**Pull request by piraka9011**
- Adds authentication for tajweed. Users are able to sign up using preliminary page, however, they need to be added by an admin to an 'evaluator' group.
- Removed unnecessary serializer code. Currently I get the following response from the frontend, which includes file and id. 
```python
AnnotatedRecordingSerializerPost(data=<QueryDict: {
'ayah_num': ['84'], 
'session_id': ['fmcd6gxbp4nnqi2ccifwwzqrlhkpftkb'], 
'hash_string': ['2211435872'], 
'recitation_mode': ['discrete'], 
'file': [<InMemoryUploadedFile: 37_84_2211435872.wav (audio/wav)>],
 'associated_demographic': [None], 
'surah_num': ['37']}>)
```

### CODE REVIEW

**Comment by abidlabs** [comment]
When I visit `http://localhost:8000/evaluation/tajweed/`, it redirects to `http://localhost:8000/accounts/login/?next=/evaluation/tajweed/`, and I get the following error:

`DoesNotExist at /accounts/login/ Site matching query does not exist.`

image

**Comment by piraka9011** [comment]
Add default sites as part of migrations. These are in `tarteel/fixtures`. So devs only need to run the usual  `makemigrations`.

Made some fixes to the demographic info model: removed the country field since its not being used and added JS to grab the platform from the user. Now we can link recordings to demographics/users better.

Some redundant JS was removed

**Comment by abidlabs** [comment]
@piraka9011, is this ready for review?

**Comment by piraka9011** [comment]
@abidlabs Go for it!

**Comment by piraka9011** [comment]
@abidlabs More features added, take a look.
Also no need for email verification in development environment, making it easier for contributors to start.
Make sure email password is setup in your `.env` file.

**Comment by abidlabs** [comment]
@piraka9011 this is solid, great work! Overall, I confirmed:

* The account sign up / sign in / sign out pages work
* Once a user has been put into the evaluator group, they have access to the tajweed evaluation page
* The tajweed page plays audio files just fine, and the user is able to submit YES or NO (in the latter case, they are asked to classify the mistake as minor or major).

I do have some suggestions / questions:
* The login page is currently not linked to from the navbar, or any other place on the website. We should add a link to the navbar at some point.
* The navbar looked a little strange on the sign out page. See this screenshot:
* An email message is printed to the console when a user creates account

image

I also have some suggestions for the Tajweed evaluation page, but ideally we should get feedback directly from people who are participating in the tajweed evaluation.
* There should be more instruction on the Evaluator page about how to evaluate the rule. (E.g. Next to ghunna, it should say, "holding the 'nun' for at least 2 counts" or something like that).
* It would be nice to see a modal (perhaps similar to the hifz evaluation page) where we show all of the Tajweed rules to give people some expectation of the kinds of things they'll be evaluating.
* We should only show for Tajweed evaluation those audio files that have already passed the hifz evaluation. It can be confusing to have an empty recording while doing the tajweed evaluation.

-----

I am going to go ahead and merge the PR, because I don't think these issues are blockers and it is good to get this PR in while @bahaa96 and @tifa2UP are refactoring the website to React.

**Pull request merged**
