### PR TITLE
Tajweed Evaluation

### PR DESCRIPTION
**Pull request by piraka9011**
This PR has:
- Authentication backend setup, no login pages yet.
- Minification taken care of by `django-compressor`. No need for the minify script.
- Support for SCSS/SASS
- Tajweed evaluation page
- Tajweed models and serializers. Note that the `TajweedEvaluation` model is linked to a `AnnotatedRecording` model via `ForeignKey`.
- Addresses issue #145 and #33 

Suggestions:
- Are we using hotjar or Google analytics?
- Seperate css and js files based on app. Make css as explicit as possible? i.e. no one big css file?

### CODE REVIEW

**Comment by piraka9011** [comment]
Updated to be compatible with recent Hifz Evaluation merge.

**Comment by piraka9011** [comment]
1. Yes `.env` should be on prod server with variables configured. 
2. Dev environment can be the same except with `DEBUG` set to true. Secret key or other variables can be whatever the developer wants since they don't affect development (to the best of my knowledge). For example I just set secret key to my own custom key while developing. You can keep this different in the env file that lives on your prod server. But yes you can add defaults.
3. Interesting, yes we can do without it. I'll take care of this.

**Comment by piraka9011** [comment]
@abidlabs Can you please try the following and let me know if it works on windows? Otherwise, I'll stick to the minify script.

```commandline
pip install rcssmin --install-option="--without-c-extensions"
pip install rjsmin --install-option="--without-c-extensions"
pip install django-compressor --upgrade
```

**Comment by abidlabs** [comment]
Seems to work, thanks @piraka9011! I'll review the rest of the PR inshaallah.

**Comment by abidlabs** [comment]
Salaam @piraka9011 I'm running into the same issue (requiring) C compiler to run on Windows for the library:
* libsass==0.16.1

In this case, I'm not able to resolve the issue by adding the --install-option="--without-c-extensions" as that option does not seem to exist for this library. Any suggestions?

**Pull request merged**
